# 1: Imports e configurações

In [1]:
# Manipulação de dados
import pandas as pd
import numpy as np

# Visualização
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# Machine Learning / Estatística
from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans

# Configurações visuais
plt.style.use("ggplot")

# Exibir todas as colunas
pd.set_option('display.max_columns', None)

# Exibir números com 2 casas decimais
pd.options.display.float_format = '{:.2f}'.format

# 2: Carregando o arquivo base via GITHUB

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/elissouza2023/sistema_agua_saneamento/main/data/dados_micromedicao.xls"

# Ler diretamente do GitHub
df = pd.read_excel(url)

print("Planilha carregada com sucesso!")

# Visualizar primeiras linhas
df.head()

Planilha carregada com sucesso!

,MATRICULA,SIT._LIG_AGUA,SIT._LIG_ESGOTO,NUMERO_HIDROMETRO,TIPO_HIDROMETRO,MARCA_HIDROMETRO,CAPACIDADE_HIDROMETRO,DIAMETRO_HIDROMETRO,CLASSE_METROLOGICA,DATA_INSTALACAO_HIDROMETRO,CATEGORIA_PRINCIPAL,NUMERO_ECONOMIAS_RES,NUMERO_ECONOMIAS_COM,NUMERO_ECONOMIAS_IND,NUMERO_ECONOMIAS_PUB,VOLUME_LIDO,VOLUME_REAL,VOLUME_FATURADO,VALOR_AGUA,VALOR_ESGOTO,VALOR_SERVICOS,VALOR_IMPOSTOS,VALOR_DESCONTOS,VALOR_TOTAL,VOLUME_LIDO_01,VOLUME_REAL_01,VOLUME_FATURADO_01,VALOR_AGUA_01,VALOR_ESGOTO_01,VALOR_SERVICOS_01,VALOR_IMPOSTOS_01,VALOR_DESCONTOS_01,VALOR_TOTAL_01,VOLUME_LIDO_02,VOLUME_REAL_02,VOLUME_FATURADO_02,VALOR_AGUA_02,VALOR_ESGOTO_02,VALOR_SERVICOS_02,VALOR_IMPOSTOS_02,VALOR_DESCONTOS_02,VALOR_TOTAL_02,VOLUME_LIDO_03,VOLUME_REAL_03,VOLUME_FATURADO_03,VALOR_AGUA_03,VALOR_ESGOTO_03,VALOR_SERVICOS_03,VALOR_IMPOSTOS_03,VALOR_DESCONTOS_03,VALOR_TOTAL_03,VOLUME_LIDO_04,VOLUME_REAL_04,VOLUME_FATURADO_04,VALOR_AGUA_04,VALOR_ESGOTO_04,VALOR_SERVICOS_04,VALOR_IMPOSTOS_04,VALOR_DESCONTOS_04,VALOR_TOTAL_04,VOLUME_LIDO_05,VOLUME_REAL_05,VOLUME_FATURADO_05,VALOR_AGUA_05,VALOR_ESGOTO_05,VALOR_SERVICOS_05,VALOR_IMPOSTOS_05,VALOR_DESCONTOS_05,VALOR_TOTAL_05,VOLUME_LIDO_06,VOLUME_REAL_06,VOLUME_FATURADO_06,VALOR_AGUA_06,VALOR_ESGOTO_06,VALOR_SERVICOS_06,VALOR_IMPOSTOS_06,VALOR_DESCONTOS_06,VALOR_TOTAL_06,VOLUME_LIDO_07,VOLUME_REAL_07,VOLUME_FATURADO_07,VALOR_AGUA_07,VALOR_ESGOTO_07,VALOR_SERVICOS_07,VALOR_IMPOSTOS_07,VALOR_DESCONTOS_07,VALOR_TOTAL_07,VOLUME_LIDO_08,VOLUME_REAL_08,VOLUME_FATURADO_08,VALOR_AGUA_08,VALOR_ESGOTO_08,VALOR_SERVICOS_08,VALOR_IMPOSTOS_08,VALOR_DESCONTOS_08,VALOR_TOTAL_08,VOLUME_LIDO_09,VOLUME_REAL_09,VOLUME_FATURADO_09,VALOR_AGUA_09,VALOR_ESGOTO_09,VALOR_SERVICOS_09,VALOR_IMPOSTOS_09,VALOR_DESCONTOS_09,VALOR_TOTAL_09,VOLUME_LIDO_10,VOLUME_REAL_10,VOLUME_FATURADO_10,VALOR_AGUA_10,VALOR_ESGOTO_10,VALOR_SERVICOS_10,VALOR_IMPOSTOS_10,VALOR_DESCONTOS_10,VALOR_TOTAL_10,VOLUME_LIDO_11,VOLUME_REAL_11,VOLUME_FATURADO_11,VALOR_AGUA_11,VALOR_ESGOTO_11,VALOR_SERVICOS_11,VALOR_IMPOSTOS_11,VALOR_DESCONTOS_11,VALOR_TOTAL_11,VOLUME_LIDO_12,VOLUME_REAL_12,VOLUME_FATURADO_12,VALOR_AGUA_12,VALOR_ESGOTO_12,VALOR_SERVICOS_12,VALOR_IMPOSTOS_12,VALOR_DESCONTOS_12,VALOR_TOTAL_12
0,1209537-0,Ativa,Ativa,Y22S490239,Unijato,MARCA A,"1,6","3/4""",Classe B,20/02/2024,Residencial,1.00,NaN,NaN,NaN,3.00,3.00,10.00,51.77,41.42,2.74,0.00,0.00,95.93,17.00,17.00,17.00,118.48,94.78,0.00,0.00,0.00,213.26,12.00,12.00,12.00,70.83,56.66,5.16,0.00,0.00,132.65,14.00,14.00,14.00,89.89,71.91,1.81,0.00,0.00,163.61,11.00,11.00,11.00,58.56,46.85,0.00,0.00,0.00,105.41,10.00,10.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,12.00,12.00,12.00,67.66,54.13,0.00,0.00,0.00,121.79,8.00,8.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,10.00,10.00,10.00,49.46,39.57,1.85,0.00,0.00,90.88,10.00,10.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,10.00,10.00,10.00,49.46,39.57,1.90,0.00,0.00,90.93,9.00,9.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,8.00,8.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03
1,1209552-4,Ativa,Ativa,Y21S226374,Unijato,MARCA A,"1,6","3/4""",Classe B,19/10/2021,Residencial,1.00,NaN,NaN,NaN,6.00,6.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,5.00,5.00,10.00,51.77,41.42,2.94,0.00,0.00,96.13,6.00,6.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,2.00,2.00,10.00,51.77,41.42,63.68,0.00,0.00,156.87,5.00,5.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,6.00,6.00,10.00,49.46,39.57,80.10,0.00,0.00,169.13,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN
2,1210192-3,Ativa,Ativa,A21AA0175469,Multijato,MARCA A,"1,5","3/4""",Classe B,14/05/2024,Residencial,1.00,NaN,NaN,NaN,21.00,21.00,21.00,156.60,125.28,0.00,0.00,0.00,281.88,28.00,28.00,28.00,234.44,187.55,0.00,0.00,0.00,421.99,34.00,34.00,34.00,313.88,251.10,0.00,0.00,0.00,564.98,29.00,29.00,29.00,247.68,198.14,0.00,0.00,0.00,445.82,28.00,28.00,28.00,223.91,179.13,0.00,0.00,0.00,403.04,29.00,29.00,29.00,236.56,189.25,0.00,0.00,0.00,425.81,26.00,26.00,26.00,198.61,158.89,0.00,0.00,0.00,357.50,34.00,34.00,34.00,299.81,239.85,0.00,0.00,0.00,539.66,34.00,34.00,34.00,299.81,239.85,0.00,0.00,0.00,539.66,27.00,27.00,27.00,211.26,169.01,0.00,0.00,0.00,380.27,32.00,32.00,32.00,274.51,219.61,0.00,0.00,0.00,494.12,26.00,26.00,26.00,198.61,158.89,0.00,0.00,0.00,357.50,28.00,28.00,28.00,223.91,179.13,0.00,0.00,0.00,403.04
3,1210205-9,Ativa,Ativa,A23AA0210661,Multijato,MARCA A,"1,5","3/4""",Classe B,21/02/2024,Residencial,1.00,NaN,NaN,NaN,30.00,30.00,30.00,260.92,208.74,0.00,0.00,0.00,469.66,20.00,20.00,20.00,147.07,117.66,15.59,0.00,0.00,280.32,26.00,26.00,26.00,207.96,166.37,0.00,0.00,0.00,374.33,35.00,35.00,35.00,327.12,261.70,0.00,0.00,0.00,588.82,22.00,22.00,22.00,158.66,126.93,168.83,0.00,0.00,454.42,27.00,27.00,27.00,211.26,169.01,0.00,0.00,0.00,380.27,32.00,32.00,32.00,274.51,219.61,0.00,0.00,0.00,494.12,28.00,28.00,28.00,223.91,179.13,0.00,0.00,0.00,403.04,25.00,25.00,25.00,185.96,148.77,0.00,0.00,0.00,334.73,17.00,17.00,17.00,113.16,90.53,34.57,0.00,0.00,238.26,19.00,19.00,19.00,131.36,105.09,35.33,0.00,0.00,271.78,31.00,31.00,31.00,261.86,209.49,0.00,0.00,0.00,471.35,26.00,26.00,26.00,198.61,158.89,0.00,0.00,0.00,357.50
4,1210231-8,Ativa,Ativa,A16B069097,ULTRASSÔNICO,MARCA B,"1,5","3/4""",Classe C,07/03/2017,Residencial,30.00,NaN,NaN,NaN,206.00,206.00,300.00,1553.10,1242.48,0.00,0.00,0.00,2795.58,213.00,213.00,300.00,1553.10,1242.48,0.00,0.00,0.00,2795.58,217.00,217.00,300.00,1553.10,1242.48,0.00,0.00,0.00,2795.58,280.00,280.00,300.00,1553.10,1242.48,0.00,0.00,0.00,2795.58,188.00,188.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,191.00,191.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,238.00,238.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,169.00,169.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,136.00,136.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,115.00,115.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,114.00,114.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,153.00,153.00,400.00,1978.40,1582.72,0.00,0.00,0.00,3561.12,159.00,159.00,400.00,1978.40,1582.72,0.00,0.00,0.00,3561.12

# 3: Conhecendo a base

In [3]:
# Informações da base
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1912 entries, 0 to 1911
Columns: 132 entries, MATRICULA to VALOR_TOTAL_12
dtypes: float64(121), object(11)
memory usage: 1.9+ MB

In [ ]:
df.describe()

,NUMERO_ECONOMIAS_RES,NUMERO_ECONOMIAS_COM,NUMERO_ECONOMIAS_IND,NUMERO_ECONOMIAS_PUB,VOLUME_LIDO,VOLUME_REAL,VOLUME_FATURADO,VALOR_AGUA,VALOR_ESGOTO,VALOR_SERVICOS,VALOR_IMPOSTOS,VALOR_DESCONTOS,VALOR_TOTAL,VOLUME_LIDO_01,VOLUME_REAL_01,VOLUME_FATURADO_01,VALOR_AGUA_01,VALOR_ESGOTO_01,VALOR_SERVICOS_01,VALOR_IMPOSTOS_01,VALOR_DESCONTOS_01,VALOR_TOTAL_01,VOLUME_LIDO_02,VOLUME_REAL_02,VOLUME_FATURADO_02,VALOR_AGUA_02,VALOR_ESGOTO_02,VALOR_SERVICOS_02,VALOR_IMPOSTOS_02,VALOR_DESCONTOS_02,VALOR_TOTAL_02,VOLUME_LIDO_03,VOLUME_REAL_03,VOLUME_FATURADO_03,VALOR_AGUA_03,VALOR_ESGOTO_03,VALOR_SERVICOS_03,VALOR_IMPOSTOS_03,VALOR_DESCONTOS_03,VALOR_TOTAL_03,VOLUME_LIDO_04,VOLUME_REAL_04,VOLUME_FATURADO_04,VALOR_AGUA_04,VALOR_ESGOTO_04,VALOR_SERVICOS_04,VALOR_IMPOSTOS_04,VALOR_DESCONTOS_04,VALOR_TOTAL_04,VOLUME_LIDO_05,VOLUME_REAL_05,VOLUME_FATURADO_05,VALOR_AGUA_05,VALOR_ESGOTO_05,VALOR_SERVICOS_05,VALOR_IMPOSTOS_05,VALOR_DESCONTOS_05,VALOR_TOTAL_05,VOLUME_LIDO_06,VOLUME_REAL_06,VOLUME_FATURADO_06,VALOR_AGUA_06,VALOR_ESGOTO_06,VALOR_SERVICOS_06,VALOR_IMPOSTOS_06,VALOR_DESCONTOS_06,VALOR_TOTAL_06,VOLUME_LIDO_07,VOLUME_REAL_07,VOLUME_FATURADO_07,VALOR_AGUA_07,VALOR_ESGOTO_07,VALOR_SERVICOS_07,VALOR_IMPOSTOS_07,VALOR_DESCONTOS_07,VALOR_TOTAL_07,VOLUME_LIDO_08,VOLUME_REAL_08,VOLUME_FATURADO_08,VALOR_AGUA_08,VALOR_ESGOTO_08,VALOR_SERVICOS_08,VALOR_IMPOSTOS_08,VALOR_DESCONTOS_08,VALOR_TOTAL_08,VOLUME_LIDO_09,VOLUME_REAL_09,VOLUME_FATURADO_09,VALOR_AGUA_09,VALOR_ESGOTO_09,VALOR_SERVICOS_09,VALOR_IMPOSTOS_09,VALOR_DESCONTOS_09,VALOR_TOTAL_09,VOLUME_LIDO_10,VOLUME_REAL_10,VOLUME_FATURADO_10,VALOR_AGUA_10,VALOR_ESGOTO_10,VALOR_SERVICOS_10,VALOR_IMPOSTOS_10,VALOR_DESCONTOS_10,VALOR_TOTAL_10,VOLUME_LIDO_11,VOLUME_REAL_11,VOLUME_FATURADO_11,VALOR_AGUA_11,VALOR_ESGOTO_11,VALOR_SERVICOS_11,VALOR_IMPOSTOS_11,VALOR_DESCONTOS_11,VALOR_TOTAL_11,VOLUME_LIDO_12,VOLUME_REAL_12,VOLUME_FATURADO_12,VALOR_AGUA_12,VALOR_ESGOTO_12,VALOR_SERVICOS_12,VALOR_IMPOSTOS_12,VALOR_DESCONTOS_12,VALOR_TOTAL_12
count,1665.00,157.00,83.00,5.00,1829.00,1829.00,1829.00,1815.00,1815.00,1815.00,1815.00,1815.00,1815.00,1815.00,1815.00,1815.00,1800.00,1800.00,1800.00,1800.00,1800.00,1800.00,1810.00,1810.00,1810.00,1798.00,1798.00,1798.00,1798.00,1798.00,1798.00,1803.00,1803.00,1803.00,1791.00,1791.00,1791.00,1791.00,1791.00,1791.00,1801.00,1801.00,1801.00,1794.00,1794.00,1794.00,1794.00,1794.00,1794.00,1796.00,1796.00,1796.00,1782.00,1782.00,1782.00,1782.00,1782.00,1782.00,1791.00,1791.00,1791.00,1781.00,1781.00,1781.00,1781.00,1781.00,1781.00,1783.00,1783.00,1783.00,1771.00,1771.00,1771.00,1771.00,1771.00,1771.00,1772.00,1772.00,1772.00,1757.00,1757.00,1757.00,1757.00,1757.00,1757.00,1761.00,1761.00,1761.00,1748.00,1748.00,1748.00,1748.00,1748.00,1748.00,1761.00,1761.00,1761.00,1745.00,1745.00,1745.00,1745.00,1745.00,1745.00,1755.00,1755.00,1755.00,1742.00,1742.00,1742.00,1742.00,1742.00,1742.00,1748.00,1748.00,1748.00,1735.00,1735.00,1735.00,1735.00,1735.00,1735.00
mean,2.72,4.64,1.01,1.00,5451.77,40.68,45.81,354.48,283.14,9.76,0.03,1.86,645.49,2236.17,33.11,40.35,290.75,232.18,3.80,0.02,2.03,524.68,6672.60,34.73,41.92,306.99,245.82,4.30,0.09,3.79,553.23,2256.14,36.68,43.92,331.09,264.80,-0.85,0.07,1.76,593.20,2825.39,35.40,41.53,289.77,231.31,7.99,0.00,8.21,520.86,2819.97,36.15,41.60,288.93,230.84,-2.18,0.02,1.56,516.01,2781.11,38.22,43.90,316.81,253.51,-2.98,0.05,2.77,564.52,2846.59,36.60,41.73,293.60,234.62,-1.27,0.02,1.13,525.81,1744.49,42.35,47.51,387.20,309.59,-161.01,0.03,1.64,534.11,4593.00,35.38,40.30,281.82,225.22,4.22,0.02,2.52,508.72,19890.79,35.94,40.90,289.05,230.74,1.56,0.03,2.88,518.43,1812.64,36.18,41.65,297.06,236.75,-1.44,0.03,4.09,528.26,4683.92,35.35,41.35,293.51,233.84,0.48,0.02,1.48,526.33
std,10.25,23.60,0.11,0.00,72976.01,132.98,152.56,1135.62,908.65,230.58,1.10,27.83,2031.88,46855.80,111.59,139.33,961.91,769.63,211.96,0.69,28.47,1718.06,81138.61,117.05,144.41,1043.18,835.35,213.69,3.72,63.04,1866.40,46955.37,121.63,148.51,1066.57,853.80,213.16,2.96,27.06,1888.45,52607.02,128.93,146.04,995.32,796.37,188.16,0.13,253.64,1741.44,52604.74,137.25,152.87,1048.77,839.10,292.30,0.85,21.18,1753.06,51805.80,133.40,153.93,1079.24,863.63,276.48,2.16,53.09,1891.74,52829.51,132.23,146.22,989.56,791.73,248.60,0.89,17.26,1732.07,41122.03,269.71,276.68,3838.49,3070.82,6689.80,1.26,20.52,1738.37,67255.71,126.78,140.36,953.69,763.05,342.49,1.01,43.58,1673.18,139425.79,129.37,142.92,1000.55,800.64,371.28,1.39,60.13,1710.92,41302.74,126.85,147.44,1026.24,821.22,320.49,1.14,101.37,1797.97,67540.02,121.67,145.22,1023.08,818.62,319.28,0.95,21.48,1786.31
min,1.00,1.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,-7019.68,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-4707.72,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-4843.82,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-4482.22,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-5640.95,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-7176.31,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-6006.44,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-5711.69,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-280240.43,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-8436.93,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-13505.58,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-7604.15,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-7254.28,0.00,0.00,0.00
25%,1.00,1.00,1.00,1.00,10.00,10.00,10.00,61.30,49.04,0.00,0.00,0.00,127.49,8.00,8.00,10.00,51.77,41.42,0.00,0.00,0.00,97.53,9.00,9.00,10.00,51.77,41.42,0.00,0.00,0.00,99.58,9.00,9.00,10.00,61.30,49.04,0.00,0.00,0.00,127.49,9.00,9.00,10.00,49.46,39.57,0.00,0.00,0.00,95.02,9.00,9.00,10.00,49.46,39.57,0.00,0.00,0.00,93.34,9.00,9.00,10.00,58.56,46.85,0.00,0.00,0.00,105.41,9.00,9.00,10.00,58.56,39.57,0.00,0.00,0.00,105.41,9.00,9.00,10.00,49.46,39.57,0.00,0.00,0.00,105.41,8.00,8.00,10.00,49.46,39.57,0.00,0.00,0.00,94.30,9.00,9.00,10.00,49.46,39.57,0.00,0.00,0.00,96.31,8.00,8.00,10.00,49.46,39.57,0.00,0.00,0.00,95.14,9.00,9.00,10.00,49.46,39.57,0.00,0.00,0.00,105.41
50%,1.00,1.00,1.00,1.00,17.00,17.00,17.00,128.01,102.41,0.00,0.00,0.00,242.30,14.00,14.00,14.00,89.89,71.91,0.00,0.00,0.00,183.40,15.00,15.00,15.00,99.42,79.54,0.00,0.00,0.00,203.96,17.00,17.00,17.00,118.48,94.78,0.00,0.00,0.00,232.37,15.00,15.00,15.00,94.96,75.97,0.00,0.00,0.00,187.31,15.00,15.00,15.00,94.96,75.97,0.00,0.00,0.00,190.00,16.00,16.00,16.00,104.06,83.25,0.00,0.00,0.00,219.47,16.00,16.00,16.00,104.06,83.25,0.00,0.00,0.00,203.69,16.00,16.00,16.00,104.06,83.25,0.00,0.00,0.00,203.69,14.00,14.00,14.00,94.96,75.97,0.00,0.00,0.00,187.31,15.00,15.00,15.00,94.96,75.97,0.00,0.00,0.00,190.36,15.00,15.00,15.00,94.96,75.97,0.00,0.00,0.00,190.16,16.00,16.00,16.00,104.06,83.25,0.00,0.00,0.00,203.69
75%,1.00,1.00,1.00,1.00,27.00,27.00,27.00,221.20,176.96,2.81,0.00,0.00,427.57,22.00,22.00,22.00,166.13,132.90,2.36,0.00,0.00,324.65,24.75,24.00,24.00,194.72,155.78,3.31,0.00,0.00,374.33,27.00,27.00,27.00,221.20,176.96,3.19,0.00,0.00,421.99,23.00,23.00,23.00,167.76,134.21,3.29,0.00,0.00,334.73,23.00,23.00,23.00,167.76,134.21,2.90,0.00,0.00,324.88,26.00,26.00,26.00,198.61,158.89,3.84,0.00,0.00,382.50,25.00,25.00,25.00,190.78,152.62,3.08,0.00,0.00,367.81,25.00,24.00,25.00,185.96,148.77,3.45,0.00,0.00,357.50,22.00,22.00,22.00,167.76,134.21,4.79,0.00,0.00,334.73,24.00,23.00,23.00,176.86,141.49,4.50,0.00,0.00,343.40,23.00,23.00,23.00,176.86,141.49,3.29,0.00,0.00,334.73,24.00,24.00,24.00,185.96,148.77,3.81,0.00,0.00,357.50
max,193.00,213.00,2.00,1.00,999422.00,3091.00,3091.00,21016.26,16813.01,1257.15,46.81,660.31,37829.27,999999.00,2913.00,2913.00,19297.44,15437.95,1257.15,29.09,706.48,34735.39,999999.00,2887.00,2887.00,19049.66,15239.73,1281.36,157.84,1712.41,34289.39,999998.00,3230.00,3230.00,22363.41,17890.73,758.72,125.18,816.54,39016.32,999997.00,2963.00,2963.00,18887.20,15109.76,1310.49,5.51,10683.36,33996.96,999995.00,3665.00,3665.00,25361.48,20289.18,565.97,35.81,493.07,38474.35,999996.00,3557.00,3557.00,24357.16,19485.72,565.97,91.07,1950.00,43842.88,1000047.00,3123.00,3123.00,20364.72,16291.77,720.77,37.61,450.43,36656.49,999997.00,9982.00,9982.00,155838.69,124670.95,720.76,52.75,400.81,35853.87,1000018.00,2877.00,2877.00,18104.60,14483.68,5108.35,42.05,1563.98,32588.28,1000639.00,2992.00,2992.00,19151.10,15320.88,720.76,58.10,2185.87,34471.98,999999.00,3258.00,3258.00,21614.74,17291.79,720.76,47.69,4021.74,38906.53,999998.00,3216.00,3216.00,21232.54,16986.03,5048.49,39.72,559.47,38218.57

In [4]:
#Rótulos de colunas
df.columns.tolist()

['MATRICULA',
 'SIT._LIG_AGUA',
 'SIT._LIG_ESGOTO',
 'NUMERO_HIDROMETRO',
 'TIPO_HIDROMETRO',
 'MARCA_HIDROMETRO',
 'CAPACIDADE_HIDROMETRO',
 'DIAMETRO_HIDROMETRO',
 'CLASSE_METROLOGICA',
 'DATA_INSTALACAO_HIDROMETRO',
 'CATEGORIA_PRINCIPAL',
 'NUMERO_ECONOMIAS_RES',
 'NUMERO_ECONOMIAS_COM',
 'NUMERO_ECONOMIAS_IND',
 'NUMERO_ECONOMIAS_PUB',
 'VOLUME_LIDO',
 'VOLUME_REAL',
 'VOLUME_FATURADO',
 'VALOR_AGUA',
 'VALOR_ESGOTO',
 'VALOR_SERVICOS',
 'VALOR_IMPOSTOS',
 'VALOR_DESCONTOS',
 'VALOR_TOTAL',
 'VOLUME_LIDO_01',
 'VOLUME_REAL_01',
 'VOLUME_FATURADO_01',
 'VALOR_AGUA_01',
 'VALOR_ESGOTO_01',
 'VALOR_SERVICOS_01',
 'VALOR_IMPOSTOS_01',
 'VALOR_DESCONTOS_01',
 'VALOR_TOTAL_01',
 'VOLUME_LIDO_02',
 'VOLUME_REAL_02',
 'VOLUME_FATURADO_02',
 'VALOR_AGUA_02',
 'VALOR_ESGOTO_02',
 'VALOR_SERVICOS_02',
 'VALOR_IMPOSTOS_02',
 'VALOR_DESCONTOS_02',
 'VALOR_TOTAL_02',
 'VOLUME_LIDO_03',
 'VOLUME_REAL_03',
 'VOLUME_FATURADO_03',
 'VALOR_AGUA_03',
 'VALOR_ESGOTO_03',
 'VALOR_SERVICOS_03',
 'VALOR_IMPOSTOS_03',
 'VALOR_DESCONTOS_03',
 'VALOR_TOTAL_03',
 'VOLUME_LIDO_04',
 'VOLUME_REAL_04',
 'VOLUME_FATURADO_04',
 'VALOR_AGUA_04',
 'VALOR_ESGOTO_04',
 'VALOR_SERVICOS_04',
 'VALOR_IMPOSTOS_04',
 'VALOR_DESCONTOS_04',
 'VALOR_TOTAL_04',
 'VOLUME_LIDO_05',
 'VOLUME_REAL_05',
 'VOLUME_FATURADO_05',
 'VALOR_AGUA_05',
 'VALOR_ESGOTO_05',
 'VALOR_SERVICOS_05',
 'VALOR_IMPOSTOS_05',
 'VALOR_DESCONTOS_05',
 'VALOR_TOTAL_05',
 'VOLUME_LIDO_06',
 'VOLUME_REAL_06',
 'VOLUME_FATURADO_06',
 'VALOR_AGUA_06',
 'VALOR_ESGOTO_06',
 'VALOR_SERVICOS_06',
 'VALOR_IMPOSTOS_06',
 'VALOR_DESCONTOS_06',
 'VALOR_TOTAL_06',
 'VOLUME_LIDO_07',
 'VOLUME_REAL_07',
 'VOLUME_FATURADO_07',
 'VALOR_AGUA_07',
 'VALOR_ESGOTO_07',
 'VALOR_SERVICOS_07',
 'VALOR_IMPOSTOS_07',
 'VALOR_DESCONTOS_07',
 'VALOR_TOTAL_07',
 'VOLUME_LIDO_08',
 'VOLUME_REAL_08',
 'VOLUME_FATURADO_08',
 'VALOR_AGUA_08',
 'VALOR_ESGOTO_08',
 'VALOR_SERVICOS_08',
 'VALOR_IMPOSTOS_08',
 'VALOR_DESCONTOS_08',
 'VALOR_TOTAL_08',
 'VOLUME_LIDO_09',
 'VOLUME_REAL_09',
 'VOLUME_FATURADO_09',
 'VALOR_AGUA_09',
 'VALOR_ESGOTO_09',
 'VALOR_SERVICOS_09',
 'VALOR_IMPOSTOS_09',
 'VALOR_DESCONTOS_09',
 'VALOR_TOTAL_09',
 'VOLUME_LIDO_10',
 'VOLUME_REAL_10',
 'VOLUME_FATURADO_10',
 'VALOR_AGUA_10',
 'VALOR_ESGOTO_10',
 'VALOR_SERVICOS_10',
 'VALOR_IMPOSTOS_10',
 'VALOR_DESCONTOS_10',
 'VALOR_TOTAL_10',
 'VOLUME_LIDO_11',
 'VOLUME_REAL_11',
 'VOLUME_FATURADO_11',
 'VALOR_AGUA_11',
 'VALOR_ESGOTO_11',
 'VALOR_SERVICOS_11',
 'VALOR_IMPOSTOS_11',
 'VALOR_DESCONTOS_11',
 'VALOR_TOTAL_11',
 'VOLUME_LIDO_12',
 'VOLUME_REAL_12',
 'VOLUME_FATURADO_12',
 'VALOR_AGUA_12',
 'VALOR_ESGOTO_12',
 'VALOR_SERVICOS_12',
 'VALOR_IMPOSTOS_12',
 'VALOR_DESCONTOS_12',
 'VALOR_TOTAL_12']

In [5]:
#Padronização das colunas, todas com letras minusculas, sem espaços, substituido Ç por c e Ã para A

df.columns = (
    df.columns
    .str.strip()
    .str.upper()
    .str.replace(' ', '_')
    .str.replace('.', '')
    .str.replace('/', '_')
    .str.replace('Ç', 'C')
    .str.replace('Ã', 'A')
    .str.replace('Á', 'A')
)

In [6]:
# Verificando colunas vazias
df.isnull().sum()

MATRICULA               0
SIT_LIG_AGUA           15
SIT_LIG_ESGOTO         36
NUMERO_HIDROMETRO      82
TIPO_HIDROMETRO        82
                     ...
VALOR_ESGOTO_12       177
VALOR_SERVICOS_12     177
VALOR_IMPOSTOS_12     177
VALOR_DESCONTOS_12    177
VALOR_TOTAL_12        177
Length: 132, dtype: int64

# 4: Tratando os dados no CSV

In [7]:
# REMOVENDO LINHAS SEM SIT_LIG_AGUA

df = df[df['SIT_LIG_AGUA'].notna()]

In [8]:
# PREENCHER NULOS NUMÉRICOS COM ZERO


colunas_numericas = df.select_dtypes(
    include=['float64', 'int64']
).columns

df[colunas_numericas] = df[colunas_numericas].fillna(0)

# Visualizar primeiras linhas
df.head()

,MATRICULA,SIT_LIG_AGUA,SIT_LIG_ESGOTO,NUMERO_HIDROMETRO,TIPO_HIDROMETRO,MARCA_HIDROMETRO,CAPACIDADE_HIDROMETRO,DIAMETRO_HIDROMETRO,CLASSE_METROLOGICA,DATA_INSTALACAO_HIDROMETRO,CATEGORIA_PRINCIPAL,NUMERO_ECONOMIAS_RES,NUMERO_ECONOMIAS_COM,NUMERO_ECONOMIAS_IND,NUMERO_ECONOMIAS_PUB,VOLUME_LIDO,VOLUME_REAL,VOLUME_FATURADO,VALOR_AGUA,VALOR_ESGOTO,VALOR_SERVICOS,VALOR_IMPOSTOS,VALOR_DESCONTOS,VALOR_TOTAL,VOLUME_LIDO_01,VOLUME_REAL_01,VOLUME_FATURADO_01,VALOR_AGUA_01,VALOR_ESGOTO_01,VALOR_SERVICOS_01,VALOR_IMPOSTOS_01,VALOR_DESCONTOS_01,VALOR_TOTAL_01,VOLUME_LIDO_02,VOLUME_REAL_02,VOLUME_FATURADO_02,VALOR_AGUA_02,VALOR_ESGOTO_02,VALOR_SERVICOS_02,VALOR_IMPOSTOS_02,VALOR_DESCONTOS_02,VALOR_TOTAL_02,VOLUME_LIDO_03,VOLUME_REAL_03,VOLUME_FATURADO_03,VALOR_AGUA_03,VALOR_ESGOTO_03,VALOR_SERVICOS_03,VALOR_IMPOSTOS_03,VALOR_DESCONTOS_03,VALOR_TOTAL_03,VOLUME_LIDO_04,VOLUME_REAL_04,VOLUME_FATURADO_04,VALOR_AGUA_04,VALOR_ESGOTO_04,VALOR_SERVICOS_04,VALOR_IMPOSTOS_04,VALOR_DESCONTOS_04,VALOR_TOTAL_04,VOLUME_LIDO_05,VOLUME_REAL_05,VOLUME_FATURADO_05,VALOR_AGUA_05,VALOR_ESGOTO_05,VALOR_SERVICOS_05,VALOR_IMPOSTOS_05,VALOR_DESCONTOS_05,VALOR_TOTAL_05,VOLUME_LIDO_06,VOLUME_REAL_06,VOLUME_FATURADO_06,VALOR_AGUA_06,VALOR_ESGOTO_06,VALOR_SERVICOS_06,VALOR_IMPOSTOS_06,VALOR_DESCONTOS_06,VALOR_TOTAL_06,VOLUME_LIDO_07,VOLUME_REAL_07,VOLUME_FATURADO_07,VALOR_AGUA_07,VALOR_ESGOTO_07,VALOR_SERVICOS_07,VALOR_IMPOSTOS_07,VALOR_DESCONTOS_07,VALOR_TOTAL_07,VOLUME_LIDO_08,VOLUME_REAL_08,VOLUME_FATURADO_08,VALOR_AGUA_08,VALOR_ESGOTO_08,VALOR_SERVICOS_08,VALOR_IMPOSTOS_08,VALOR_DESCONTOS_08,VALOR_TOTAL_08,VOLUME_LIDO_09,VOLUME_REAL_09,VOLUME_FATURADO_09,VALOR_AGUA_09,VALOR_ESGOTO_09,VALOR_SERVICOS_09,VALOR_IMPOSTOS_09,VALOR_DESCONTOS_09,VALOR_TOTAL_09,VOLUME_LIDO_10,VOLUME_REAL_10,VOLUME_FATURADO_10,VALOR_AGUA_10,VALOR_ESGOTO_10,VALOR_SERVICOS_10,VALOR_IMPOSTOS_10,VALOR_DESCONTOS_10,VALOR_TOTAL_10,VOLUME_LIDO_11,VOLUME_REAL_11,VOLUME_FATURADO_11,VALOR_AGUA_11,VALOR_ESGOTO_11,VALOR_SERVICOS_11,VALOR_IMPOSTOS_11,VALOR_DESCONTOS_11,VALOR_TOTAL_11,VOLUME_LIDO_12,VOLUME_REAL_12,VOLUME_FATURADO_12,VALOR_AGUA_12,VALOR_ESGOTO_12,VALOR_SERVICOS_12,VALOR_IMPOSTOS_12,VALOR_DESCONTOS_12,VALOR_TOTAL_12
0,1209537-0,Ativa,Ativa,Y22S490239,Unijato,MARCA A,"1,6","3/4""",Classe B,20/02/2024,Residencial,1.00,0.00,0.00,0.00,3.00,3.00,10.00,51.77,41.42,2.74,0.00,0.00,95.93,17.00,17.00,17.00,118.48,94.78,0.00,0.00,0.00,213.26,12.00,12.00,12.00,70.83,56.66,5.16,0.00,0.00,132.65,14.00,14.00,14.00,89.89,71.91,1.81,0.00,0.00,163.61,11.00,11.00,11.00,58.56,46.85,0.00,0.00,0.00,105.41,10.00,10.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,12.00,12.00,12.00,67.66,54.13,0.00,0.00,0.00,121.79,8.00,8.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,10.00,10.00,10.00,49.46,39.57,1.85,0.00,0.00,90.88,10.00,10.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,10.00,10.00,10.00,49.46,39.57,1.90,0.00,0.00,90.93,9.00,9.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,8.00,8.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03
1,1209552-4,Ativa,Ativa,Y21S226374,Unijato,MARCA A,"1,6","3/4""",Classe B,19/10/2021,Residencial,1.00,0.00,0.00,0.00,6.00,6.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,5.00,5.00,10.00,51.77,41.42,2.94,0.00,0.00,96.13,6.00,6.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,2.00,2.00,10.00,51.77,41.42,63.68,0.00,0.00,156.87,5.00,5.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,6.00,6.00,10.00,49.46,39.57,80.10,0.00,0.00,169.13,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,1210192-3,Ativa,Ativa,A21AA0175469,Multijato,MARCA A,"1,5","3/4""",Classe B,14/05/2024,Residencial,1.00,0.00,0.00,0.00,21.00,21.00,21.00,156.60,125.28,0.00,0.00,0.00,281.88,28.00,28.00,28.00,234.44,187.55,0.00,0.00,0.00,421.99,34.00,34.00,34.00,313.88,251.10,0.00,0.00,0.00,564.98,29.00,29.00,29.00,247.68,198.14,0.00,0.00,0.00,445.82,28.00,28.00,28.00,223.91,179.13,0.00,0.00,0.00,403.04,29.00,29.00,29.00,236.56,189.25,0.00,0.00,0.00,425.81,26.00,26.00,26.00,198.61,158.89,0.00,0.00,0.00,357.50,34.00,34.00,34.00,299.81,239.85,0.00,0.00,0.00,539.66,34.00,34.00,34.00,299.81,239.85,0.00,0.00,0.00,539.66,27.00,27.00,27.00,211.26,169.01,0.00,0.00,0.00,380.27,32.00,32.00,32.00,274.51,219.61,0.00,0.00,0.00,494.12,26.00,26.00,26.00,198.61,158.89,0.00,0.00,0.00,357.50,28.00,28.00,28.00,223.91,179.13,0.00,0.00,0.00,403.04
3,1210205-9,Ativa,Ativa,A23AA0210661,Multijato,MARCA A,"1,5","3/4""",Classe B,21/02/2024,Residencial,1.00,0.00,0.00,0.00,30.00,30.00,30.00,260.92,208.74,0.00,0.00,0.00,469.66,20.00,20.00,20.00,147.07,117.66,15.59,0.00,0.00,280.32,26.00,26.00,26.00,207.96,166.37,0.00,0.00,0.00,374.33,35.00,35.00,35.00,327.12,261.70,0.00,0.00,0.00,588.82,22.00,22.00,22.00,158.66,126.93,168.83,0.00,0.00,454.42,27.00,27.00,27.00,211.26,169.01,0.00,0.00,0.00,380.27,32.00,32.00,32.00,274.51,219.61,0.00,0.00,0.00,494.12,28.00,28.00,28.00,223.91,179.13,0.00,0.00,0.00,403.04,25.00,25.00,25.00,185.96,148.77,0.00,0.00,0.00,334.73,17.00,17.00,17.00,113.16,90.53,34.57,0.00,0.00,238.26,19.00,19.00,19.00,131.36,105.09,35.33,0.00,0.00,271.78,31.00,31.00,31.00,261.86,209.49,0.00,0.00,0.00,471.35,26.00,26.00,26.00,198.61,158.89,0.00,0.00,0.00,357.50
4,1210231-8,Ativa,Ativa,A16B069097,ULTRASSÔNICO,MARCA B,"1,5","3/4""",Classe C,07/03/2017,Residencial,30.00,0.00,0.00,0.00,206.00,206.00,300.00,1553.10,1242.48,0.00,0.00,0.00,2795.58,213.00,213.00,300.00,1553.10,1242.48,0.00,0.00,0.00,2795.58,217.00,217.00,300.00,1553.10,1242.48,0.00,0.00,0.00,2795.58,280.00,280.00,300.00,1553.10,1242.48,0.00,0.00,0.00,2795.58,188.00,188.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,191.00,191.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,238.00,238.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,169.00,169.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,136.00,136.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,115.00,115.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,114.00,114.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,153.00,153.00,400.00,1978.40,1582.72,0.00,0.00,0.00,3561.12,159.00,159.00,400.00,1978.40,1582.72,0.00,0.00,0.00,3561.12

In [9]:
# PREENCHIMENTO DA CATEGORIA_PRINCIPAL


df['CATEGORIA_PRINCIPAL'] = (
    df['CATEGORIA_PRINCIPAL']
    .fillna('NAO INFORMADO')
)

# Visualizar primeiras linhas
df.head(20)

,MATRICULA,SIT_LIG_AGUA,SIT_LIG_ESGOTO,NUMERO_HIDROMETRO,TIPO_HIDROMETRO,MARCA_HIDROMETRO,CAPACIDADE_HIDROMETRO,DIAMETRO_HIDROMETRO,CLASSE_METROLOGICA,DATA_INSTALACAO_HIDROMETRO,CATEGORIA_PRINCIPAL,NUMERO_ECONOMIAS_RES,NUMERO_ECONOMIAS_COM,NUMERO_ECONOMIAS_IND,NUMERO_ECONOMIAS_PUB,VOLUME_LIDO,VOLUME_REAL,VOLUME_FATURADO,VALOR_AGUA,VALOR_ESGOTO,VALOR_SERVICOS,VALOR_IMPOSTOS,VALOR_DESCONTOS,VALOR_TOTAL,VOLUME_LIDO_01,VOLUME_REAL_01,VOLUME_FATURADO_01,VALOR_AGUA_01,VALOR_ESGOTO_01,VALOR_SERVICOS_01,VALOR_IMPOSTOS_01,VALOR_DESCONTOS_01,VALOR_TOTAL_01,VOLUME_LIDO_02,VOLUME_REAL_02,VOLUME_FATURADO_02,VALOR_AGUA_02,VALOR_ESGOTO_02,VALOR_SERVICOS_02,VALOR_IMPOSTOS_02,VALOR_DESCONTOS_02,VALOR_TOTAL_02,VOLUME_LIDO_03,VOLUME_REAL_03,VOLUME_FATURADO_03,VALOR_AGUA_03,VALOR_ESGOTO_03,VALOR_SERVICOS_03,VALOR_IMPOSTOS_03,VALOR_DESCONTOS_03,VALOR_TOTAL_03,VOLUME_LIDO_04,VOLUME_REAL_04,VOLUME_FATURADO_04,VALOR_AGUA_04,VALOR_ESGOTO_04,VALOR_SERVICOS_04,VALOR_IMPOSTOS_04,VALOR_DESCONTOS_04,VALOR_TOTAL_04,VOLUME_LIDO_05,VOLUME_REAL_05,VOLUME_FATURADO_05,VALOR_AGUA_05,VALOR_ESGOTO_05,VALOR_SERVICOS_05,VALOR_IMPOSTOS_05,VALOR_DESCONTOS_05,VALOR_TOTAL_05,VOLUME_LIDO_06,VOLUME_REAL_06,VOLUME_FATURADO_06,VALOR_AGUA_06,VALOR_ESGOTO_06,VALOR_SERVICOS_06,VALOR_IMPOSTOS_06,VALOR_DESCONTOS_06,VALOR_TOTAL_06,VOLUME_LIDO_07,VOLUME_REAL_07,VOLUME_FATURADO_07,VALOR_AGUA_07,VALOR_ESGOTO_07,VALOR_SERVICOS_07,VALOR_IMPOSTOS_07,VALOR_DESCONTOS_07,VALOR_TOTAL_07,VOLUME_LIDO_08,VOLUME_REAL_08,VOLUME_FATURADO_08,VALOR_AGUA_08,VALOR_ESGOTO_08,VALOR_SERVICOS_08,VALOR_IMPOSTOS_08,VALOR_DESCONTOS_08,VALOR_TOTAL_08,VOLUME_LIDO_09,VOLUME_REAL_09,VOLUME_FATURADO_09,VALOR_AGUA_09,VALOR_ESGOTO_09,VALOR_SERVICOS_09,VALOR_IMPOSTOS_09,VALOR_DESCONTOS_09,VALOR_TOTAL_09,VOLUME_LIDO_10,VOLUME_REAL_10,VOLUME_FATURADO_10,VALOR_AGUA_10,VALOR_ESGOTO_10,VALOR_SERVICOS_10,VALOR_IMPOSTOS_10,VALOR_DESCONTOS_10,VALOR_TOTAL_10,VOLUME_LIDO_11,VOLUME_REAL_11,VOLUME_FATURADO_11,VALOR_AGUA_11,VALOR_ESGOTO_11,VALOR_SERVICOS_11,VALOR_IMPOSTOS_11,VALOR_DESCONTOS_11,VALOR_TOTAL_11,VOLUME_LIDO_12,VOLUME_REAL_12,VOLUME_FATURADO_12,VALOR_AGUA_12,VALOR_ESGOTO_12,VALOR_SERVICOS_12,VALOR_IMPOSTOS_12,VALOR_DESCONTOS_12,VALOR_TOTAL_12
0,1209537-0,Ativa,Ativa,Y22S490239,Unijato,MARCA A,"1,6","3/4""",Classe B,20/02/2024,Residencial,1.00,0.00,0.00,0.00,3.00,3.00,10.00,51.77,41.42,2.74,0.00,0.00,95.93,17.00,17.00,17.00,118.48,94.78,0.00,0.00,0.00,213.26,12.00,12.00,12.00,70.83,56.66,5.16,0.00,0.00,132.65,14.00,14.00,14.00,89.89,71.91,1.81,0.00,0.00,163.61,11.00,11.00,11.00,58.56,46.85,0.00,0.00,0.00,105.41,10.00,10.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,12.00,12.00,12.00,67.66,54.13,0.00,0.00,0.00,121.79,8.00,8.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,10.00,10.00,10.00,49.46,39.57,1.85,0.00,0.00,90.88,10.00,10.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,10.00,10.00,10.00,49.46,39.57,1.90,0.00,0.00,90.93,9.00,9.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,8.00,8.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03
1,1209552-4,Ativa,Ativa,Y21S226374,Unijato,MARCA A,"1,6","3/4""",Classe B,19/10/2021,Residencial,1.00,0.00,0.00,0.00,6.00,6.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,5.00,5.00,10.00,51.77,41.42,2.94,0.00,0.00,96.13,6.00,6.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,2.00,2.00,10.00,51.77,41.42,63.68,0.00,0.00,156.87,5.00,5.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,6.00,6.00,10.00,49.46,39.57,80.10,0.00,0.00,169.13,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,1210192-3,Ativa,Ativa,A21AA0175469,Multijato,MARCA A,"1,5","3/4""",Classe B,14/05/2024,Residencial,1.00,0.00,0.00,0.00,21.00,21.00,21.00,156.60,125.28,0.00,0.00,0.00,281.88,28.00,28.00,28.00,234.44,187.55,0.00,0.00,0.00,421.99,34.00,34.00,34.00,313.88,251.10,0.00,0.00,0.00,564.98,29.00,29.00,29.00,247.68,198.14,0.00,0.00,0.00,445.82,28.00,28.00,28.00,223.91,179.13,0.00,0.00,0.00,403.04,29.00,29.00,29.00,236.56,189.25,0.00,0.00,0.00,425.81,26.00,26.00,26.00,198.61,158.89,0.00,0.00,0.00,357.50,34.00,34.00,34.00,299.81,239.85,0.00,0.00,0.00,539.66,34.00,34.00,34.00,299.81,239.85,0.00,0.00,0.00,539.66,27.00,27.00,27.00,211.26,169.01,0.00,0.00,0.00,380.27,32.00,32.00,32.00,274.51,219.61,0.00,0.00,0.00,494.12,26.00,26.00,26.00,198.61,158.89,0.00,0.00,0.00,357.50,28.00,28.00,28.00,223.91,179.13,0.00,0.00,0.00,403.04
3,1210205-9,Ativa,Ativa,A23AA0210661,Multijato,MARCA A,"1,5","3/4""",Classe B,21/02/2024,Residencial,1.00,0.00,0.00,0.00,30.00,30.00,30.00,260.92,208.74,0.00,0.00,0.00,469.66,20.00,20.00,20.00,147.07,117.66,15.59,0.00,0.00,280.32,26.00,26.00,26.00,207.96,166.37,0.00,0.00,0.00,374.33,35.00,35.00,35.00,327.12,261.70,0.00,0.00,0.00,588.82,22.00,22.00,22.00,158.66,126.93,168.83,0.00,0.00,454.42,27.00,27.00,27.00,211.26,169.01,0.00,0.00,0.00,380.27,32.00,32.00,32.00,274.51,219.61,0.00,0.00,0.00,494.12,28.00,28.00,28.00,223.91,179.13,0.00,0.00,0.00,403.04,25.00,25.00,25.00,185.96,148.77,0.00,0.00,0.00,334.73,17.00,17.00,17.00,113.16,90.53,34.57,0.00,0.00,238.26,19.00,19.00,19.00,131.36,105.09,35.33,0.00,0.00,271.78,31.00,31.00,31.00,261.86,209.49,0.00,0.00,0.00,471.35,26.00,26.00,26.00,198.61,158.89,0.00,0.00,0.00,357.50
4,1210231-8,Ativa,Ativa,A16B069097,ULTRASSÔNICO,MARCA B,"1,5","3/4""",Classe C,07/03/2017,Residencial,30.00,0.00,0.00,0.00,206.00,206.00,300.00,1553.10,1242.48,0.00,0.00,0.00,2795.58,213.00,213.00,300.00,1553.10,1242.48,0.00,0.00,0.00,2795.58,217.00,217.00,300.00,1553.10,1242.48,0.00,0.00,0.00,2795.58,280.00,280.00,300.00,1553.10,1242.48,0.00,0.00,0.00,2795.58,188.00,188.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,191.00,191.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,238.00,238.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,169.00,169.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,136.00,136.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,115.00,115.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,114.00,114.00,300.00,1483.80,1187.04,0.00,0.00,0.00,2670.84,153.00,153.00,400.00,1978.40,1582.72,0.00,0.00,0.00,3561.12,159.00,159.00,400.00,1978.40,1582.72,0.00,0.00,0.00,3561.12
5,1211680-7,Ativa,Ativa,Y24L183775,Unijato,MARCA C,"1,6","3/4""",Classe A,19/05/2025,Industrial,0.00,0.00,1.00,0.00,7.00,7.00,10.00,76.82,61.46,2.88,0.00,0.00,141.16,4.00,4.00,10.00,76.82,61.46,2.91,0.00,0.00,141.19,7.00,7.00,10.00,76.82,61.46,3.26,0.00,0.00,141.54,10.00,10.00,10.00,76.82,61.46,2.79,0.00,0.00,141.07,10.00,10.00,10.00,73.39,58.71,0.00,0.00,0.00,132.10,8.00,8.00,10.00,73.39,58.71,3.04,0.00,0.00,135.14,9.00,9.00,10.00,73.39,58.71,3.66,0.00,0.00,135.76,7.00,7.00,10.00,73.39,58.71,3.94,0.00,0.00,136.04,11.00,11.00,11.00,85.18,68.14,3.44,0.00,0.00,156.76,12.00,12.00,12.00,96.97,77.58,4.68,0.00,0.00,179.23,11.00,11.00,11.00,85.18,68.14,3.29,0.00,0.00,156.61,14.00,14.00,14.00,120.55,96.44,5.87,0.00,0.00,222.86,9.00,9.00,10.00,73.39,58.71,4.85,0.00,0.00,136.95
6,1213365-5,Cancelada,Cancelada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Residencial,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,10.00,10.00,10.00,49.46,39.57,0.00,0.00,4.20,84.83,0.00,0.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,0.00,0.00,10.00,49.46,39.57,0.00,0.00,89.03,0.00,0.00,0.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,2.00,2.00,10.00,49.46,39.57,4.20,0.00,0.00,93.23,2.00,2.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03
7,1213368-0,Ativa,Ativa,Y19S042835,Unijato,MARCA D,"1,6","3/4""",Classe B,08/11/2019,Residencial,1.00,0.00,0.00,0.00,10.00,10.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,11.00,11.00,11.00,61.30,49.04,0.00,0.00,0.00,110.34,12.00,12.00,12.00,70.83,56.66,0.00,0.00,0.00,127.49,12.00,12.00,12.00,70.83,56.66,0.00,0.00,0.00,127.49,11.00,11.00,11.00,58.56,46.85,0.00,0.00,0.00,105.41,12.00,12.00,12.00,67.66,54.13,0.00,0.00,0.00,121.79,9.00,9.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,15.00,15.00,15.00,94.96,75.97,0.00,0.00,0.00,170.93,19.00,19.00,19.00,131.36,105.09,0.00,0.00,0.00,236.45,14.00,14.00,14.00,85.86,68.69,2.08,0.00,0.00,156.63,10.00,10.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,10.00,10.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,8.00,8.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03
8,1213369-8,Ativa,Ativa,Y21S506098,Unijato,MARCA A,"1,6","3/4""",Classe B,17/07/2023,Residencial,1.00,0.00,0.00,0.00,17.00,17.00,17.00,118.48,94.78,0.00,0.00,0.00,213.26,20.00,20.00,20.00,147.07,117.66,0.00,0.00,0.00,264.73,10.00,10.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,2.00,2.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,6.00,6.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,14.00,14.00,14.00,85.86,68.69,0.00,0.00,0.00,154.55,27.00,27.00,27.00,211.26,169.01,0.00,0.00,0.00,380.27,12.00,12.00,12.00,67.66,54.13,0.00,0.00,0.00,121.79,14.00,14.00,14.00,85.86,68.69,0.00,0.00,0.00,154.55,30.00,30.00,30.00,249.21,199.37,0.00,0.00,0.00,448.58,17.00,17.00,17.00,113.16,90.53,0.00,0.00,0.00,203.69,15.00,15.00,15.00,94.96,75.97,0.00,0.00,0.00,170.93,5.00,5.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03
9,1213381-7,Ativa,Ativa,Y22S490451,Unijato,MARCA A,"1,6","3/4""",Classe B,27/03/2024,Residencial,1.00,0.00,0.00,0.00,12.00,12.00,12.00,70.83,56.66,0.00,0.00,0.00,127.49,10.00,10.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,11.00,11.00,11.00,61.30,49.04,0.00,0.00,0.00,110.34,15.00,15.00,15.00,99.42,79.54,0.00,0.00,0.00,178.96,12.00,12.00,12.00,67.66,54.13,0.00,0.00,0.00,121.79,13.00,13.00,13.00,76.76,61.41,3.81,0.00,0.00,141.98,10.00,10.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,14.00,14.00,14.00,85.86,68.69,0.00,0.00,0.00,154.55,13.00,13.00,13.00,76.76,61.41,0.00,0.00,0.00,138.17,12.00,12.00,12.00,67.66,54.13,0.00,0.00,0.00,121.79,11.00,11.00,11.00,58.56,46.85,0.00,0.00,0.00,105.41,11.00,11.00,11.00,58.56,46.85,0.00,0.00,0.00,105.41,12.00,12.00,12.00,67.66,54.13,0.00,0.00,0.00,121.79
10,1215701-5,Ativa,Ativa,Y24L094694,Unijato,MARCA C,"1,6","3/4""",Classe A,16/07/2025,Residencial,1.00,0.00,0.00,0.00,0.00,0.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,0.00,0.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,1.00,1.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,0.00,0.00,10.00,51.77,41.42,52.76,0.00,0.00,145.95,0.00,0.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,0.00,0.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,1.00,1.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,64.00,64.00,64.00,721.17,576.94,0.00,0.00,0.00,1298.11,1.00,1.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,1.00,1.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,1.00,1.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,1.00,1.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,0.00,0.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03
11,1215707-4,Ativa,Ativa,Y19S042739,UNIJATO - PRÉ EQUIPADO,MARCA D,"1,6","3/4""",Classe B,22/01/2020,Residencial,1.00,0.00,0.00,0.00,17.00,17.00,17.00,118.48,94.78,0.00,0.00,0.00,213.26,13.00,13.00,13.00,80.36,64.29,0.00,0.00,0.00,144.65,17.00,17.00,17.00,118.48,94.78,5.37,0.00,0.00,218.63,19.00,19.00,19.00,137.54,110.03,13.88,0.00,0.00,261.45,13.00,13.00,13.00,76.76,61.41,0.00,0.00,0.00,138.17,16.00,16.00,16.00,104.06,83.25,0.00,0.00,0.00,187.31,17.00,17.00,17.00,113.16,90.53,0.00,0.00,0.00,203.69,15.00,15.00,15.00,94.96,75.97,0.00,0.00,0.00,170.93,14.00,14.00,14.00,85.86,68.69,0.00,0.00,0.00,154.55,13.00,13.00,13.00,76.76,61.41,21.87,0.00,0.00,160.04,11.00,11.00,11.00,58.56,46.85,0.00,0.00,0.00,105.41,16.00,16.00,16.00,104.06,83.25,0.00,0.00,0.00,187.31,14.00,14.00,14.00,85.86,68.69,0.00,0.00,0.00,154.55
12,1215712-0,Ativa,Ativa,Y22S490032,Unijato,MARCA A,"1,6","3/4""",Classe B,20/12/2023,Residencial,1.00,0.00,0.00,0.00,4.00,4.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,4.00,4.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,2.00,2.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,2.00,2.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,4.00,4.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,5.00,5.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,3.00,3.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,4.00,4.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,3.00,3.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,3.00,3.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,4.00,4.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,3.00,3.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03,3.00,3.00,10.00,49.46,39.57,0.00,0.00,0.00,89.03
13,1215716-3,Ativa,Ativa,Y19S043444,Unijato,MARCA D,"1,6","3/4""",Classe B,13/09/2019,Residencial,1.00,0.00,0.00,0.00,17.00,17.00,17.00,118.48,94.78,4.85,0.00,0.00,218.11,14.00,14.00,14.00,89.89,71.91,4.56,0.00,0.00,166.36,14.00,14.00,14.00,89.89,71.91,3.55,0.00,0.00,165.35,17.00,17.00,17.00,118.48,94.78,3.65,0.00,0.00,216.91,14.00,14.00,14.00,85.86,68.69,4.48,0.00,0.00,159.03,15.00,15.00,15.00,94.96,75.97,0.00,0.00,0.00,170.93,17.00,17.00,17.00,113.16,90.53,6.48,0.00,0.00,210.17,15.00,15.00,15.00,94.96,75.97,0.00,0.00,0.00,170.93,17.00,17.00,17.00,113.16,90.53,2.18,0.00,0.00,205.87,17.00,17.00,17.00,113.16,90.53,3.19,0.00,0.00,206.88,15.00,15.00,15.00,94.96,0.00,2.31,0.00,0.00,97.27,20.00,20.00,20.00,140.46,0.00,2.69,0.00,0.00,143.15,16.00,16.00,16.00,104.06,0.00,2.30,0.00,0.00,106.36
14,1217395-9,Ativa,Ativa,Y24L183803,Unijato,MARCA C,"1,6","3/4""",Classe A,17/04/2025,Residencial,1.00,0.00,0.00,0.00,11.00,11.00,11.00,61.30,49.04,0.00,0.00,0.00,110.34,8.00,8.00,10.00,51.77,41.42,0.00,0.00,0.00,93.19,11.00,11.00,11.00,61.30,49.04,0.00,0.00,0.00,110.34,13.00,13.00,13.00,80.36,64.29,4.22,0.00,0.00,148.87,12.00,12.00,12.00,67.66,54.13,6.21,0.00,0.00,128.00,15.00,15.00,15.00,94.96,75.97,18.10,0.00,0.00,189.03,18.00,18.00,18.00,122.26,97.81,53.96,0.00,0.00,274.03,17.00,17.00,17.00,113.16,90.53,0.00,0.00,0.00,203.69,29.00,29.00,29.00,236.56,189.25,0.00,0.00,0.00,425.81,20.00,20.00,20.00,140.46,112.37,0.00,0.00,0.00,252.83,17.00,17.00,17.00,113.16,90.53,0.00,0.00,0.00,203.69,31.00,31.00,31.00,261.86,209.49,-243.09,0.00,0.00,228.26,999938.00,12.00,12.00,67.66,54.13,0.00,0.00,0.00,121.79
15,1217684-2,Ativa,Ativa,Y19S048527,UNIJATO - PRÉ EQUIPADO,MARCA D,"1,6","3/4""",Classe B,27/06/2019,Residencial,1.00,0.00,0.00,0.00,20.00,20.00,20.00,147.07,117.66,18.93,0.00,0.00,283.66,16.00,16.00,16.00,108.95,87.16,17.24,0.00,0.00,213.35,17.00,17.00,17.00,118.48,94.78,9.84,0.00,0.00,223.10,23.00,23.00,23.00,175.66,140.53,0.00,0.00,0.00,316.19,19.00,19.00,19.00,131.36,105.09,11.21,0.00,0.00,247.66,17.00,17.00,17.00,113.16,90.53,7.79,0.00,0.00,211.48,18.00,18.00,18.00,122.26,97.81,7.11,0.00,0.00,227.18,21.00,21.00,21.00,149.56,119.65,9.01,0.00,0.00,278.22,17.00,17.00,17.00,113.16,90.53,7.05,0.00,0.00,210.74,15.00,15.00,15.00,94.96,75.97,12.89,0.00,0.00,183.82,18.00,18.00,18.00,122.26,97.81,15.16,0.00,0.00,235.23,17.00,17.00,17.00,113.16,90.53,0.00,0.00,0.00,203.69,26.00,26.00,26.00,198.61,158.89,11.04,0.00,0.00,368.54
16,1219702-5,Cancelada,Ativa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Residencial,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
17,1219704-1,Ativa,Ativa,Y22S490242,Unijato,MARCA A,"1,6","3/4""",Classe B,20/02/2024,Residencial,1.00,0.00,0.00,0.00,18.00,18.00,18.00,128.01,102.41,0.00,0.00,0.00,230.42,16.00,16.00,16.00,108.95,87.16,0.00,0.00,0.00,196.11,16.00,16.00,16.00,108.95,87.16,0.00,0.00,0.00,196.11,26.00,26.00,26.00,207.96,166.37,0.00,0.00,0.00,374.33,15.00,15.00,15.00,94.96,75.97,0.00,0.00,0.00,170.93,19.00,19.00,19.00,131.36,105.09,0.00,0.00,0.00,236.45,25.00,25.00,25.00,185.96,148.77,0.00,0.00,0.00,334.73,18.00,18.00,18.00,122.26,97.81,0.00,0.00,0.00,220.07,17.00,17.00,17.00,113.16,90.53,0.00,0.00,0.00,203.69,19.00,19.00,19.00,131.36,105.09,0.00,0.00,0.00,236.45,17.00,17.00,17.00,113.16,90.53,0.00,0.00,0.00,203.69,20.00,20.00,20.00,140.46,112.37,0.00,0.00,0.00,252.83,19.00,19.00,19.00,131.36,105.09,0.00,0.00,0.00,236.45
18,1219707-6,Ativa,Ativa,Y22S490224,Unijato,MARCA A,"1,6","3/4""",Classe B,07/12/2023,Comercial,0.00,1.00,0.00,0.00,3.00,3.00,10.00,76.29,61.03,-137.32,0.00,0.00,0.00,0.00,0.00,10.00,76.29,61.03,-137.32,0.00,0.00,0.00,998156.00,10.00,10.00,76.29,61.03,-137.32,0.00,0.00,0.00,1848.00,74.00,74.00,866.05,692.84,-1558.89,0.00,0.00,0.00,1.00,1.00,10.00,72.88,58.30,-131.18,0.00,0.00,0.00,5.00,5.00,10.00,72.88,58.30,-131.18,0.00,0.00,0.00,0.00,0.00,10.00,72.88,58.30,-131.18,0.00,0.00,0.00,1.00,1.00,10.00,72.88,58.30,-131.18,0.00,0.00,0.00,2.00,2.00,10.00,72.88,58.30,-131.18,0.00,0.00,0.00,6.00,6.00,10.00,72.88,58.30,-131.18,0.00,0.00,0.00,2.00,2.00,10.00,72.88,58.30,-131.18,0.00,0.00,0.00,2.00,2.00,10.00,72.88,58.30,-131.18,0.00,0.00,0.00,4.00,4.00,10.00,72.88,58.30,-131.18,0.00,0.00,0.00
19,1219708-4,Ativa,Ativa,Y22S490229,Unijato,MARCA A,"1,6","3/4""",Classe B,07/12/2023,Industrial,0.00,0.00,1.00,0.00,10.00,10.00,10.00,76.82,61.46,0.00,0.00,0.00,138.28,0.00,0.00,10.00,76.82,61.46,0.00,0.00,0.00,138.28,0.00,0.00,10.00,76.82,61.46,0.00,0.00,0.00,138.28,10.00,10.00,10.00,76.82,61.46,0.00,0.00,0.00,138.28,10.00,10.00,10.00,73.39,58.71,0.00,0.00,0.00,132.10,0.00,0.00,10.00,73.39,58.71,0.00,0.00,0.00,132.10,0.00,0.00,10.00,73.39,58.71,0.00,0.00,0.00,132.10,1.00,1.00,10.00,73.39,58.71,0.00,0.00,0.00,132.10,0.00,0.00,10.00,73.39,58.71,3.52,0.00,0.00,135.62,0.00,0.00,10.00,73.39,58.71,0.00,0.00,0.00,132.10,0.00,0.00,10.00,73.39,58.71,0.00,0.00,0.00,132.10,0.00,0.00,10.00,73.39,58.71,0.00,0.00,0.00,132.10,1.00,1.00,10.00,73.39,58.71,0.00,0.00,0.00,132.10

In [10]:
# Convertendo data
df['DATA_INSTALACAO_HIDROMETRO'] = pd.to_datetime(
    df['DATA_INSTALACAO_HIDROMETRO'],
    errors='coerce'
)

/tmp/ipykernel_20735/1856166289.py:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['DATA_INSTALACAO_HIDROMETRO'] = pd.to_datetime(

In [11]:
#verificando duplicadas
df.duplicated().sum()

np.int64(0)

# 5: Salvando o DataFrame

In [12]:
# Exportando a base tratada para csv

df.to_csv(
    'dados_tratados.csv',
    index=False,
    encoding='utf-8'
)

print("CSV salvo com sucesso!")

CSV salvo com sucesso!

In [13]:
# VISUALIZANDO TIPOS DAS COLUNAS


df.dtypes

MATRICULA              object
SIT_LIG_AGUA           object
SIT_LIG_ESGOTO         object
NUMERO_HIDROMETRO      object
TIPO_HIDROMETRO        object
                       ...
VALOR_ESGOTO_12       float64
VALOR_SERVICOS_12     float64
VALOR_IMPOSTOS_12     float64
VALOR_DESCONTOS_12    float64
VALOR_TOTAL_12        float64
Length: 132, dtype: object

# Engenharia de atributos

# 6. Consumo Acumulado do período

In [14]:
# Calculando a receita anual
colunas_consumo = [
    col for col in df.columns
    if 'VOLUME_FATURADO_' in col
]

df['CONSUMO_ACUMULADO'] = (
    df[colunas_consumo]
    .sum(axis=1)
)

/tmp/ipykernel_20735/1606267118.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['CONSUMO_ACUMULADO'] = (

# 7. Receita Acumulada

In [15]:
# RECEITA ACUMULADA do período

colunas_receita = [
    col for col in df.columns
    if 'VALOR_TOTAL_' in col
]

df['RECEITA_ACUMULADA'] = (
    df[colunas_receita]
    .sum(axis=1)
)

/tmp/ipykernel_20735/4210876551.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['RECEITA_ACUMULADA'] = (

# 8. Consumo médio Mensal

In [16]:
# CONSUMO MEDIO


df['CONSUMO_MEDIO'] = (
    df[colunas_consumo]
    .mean(axis=1)
)

/tmp/ipykernel_20735/3449122368.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['CONSUMO_MEDIO'] = (

# 9. Receita média mensal

In [17]:
# RECEITA MEDIA


df['RECEITA_MEDIA'] = (
    df[colunas_receita]
    .mean(axis=1)
)

/tmp/ipykernel_20735/890901606.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['RECEITA_MEDIA'] = (

# 10. Idade do Hidrometro

In [18]:
# IDADE DO HIDROMETRO


df['IDADE_HIDROMETRO'] = (
    (
        pd.Timestamp.today() -
        df['DATA_INSTALACAO_HIDROMETRO']
    ).dt.days / 365
).round(1)

/tmp/ipykernel_20735/452977606.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['IDADE_HIDROMETRO'] = (

# 11. Ticket médio por m³

In [19]:
# TICKET MEDIO POR M³
df['TICKET_MEDIO_M3'] = np.where(
    df['CONSUMO_ACUMULADO'] > 0,
    df['RECEITA_ACUMULADA'] / df['CONSUMO_ACUMULADO'],
    0
)

/tmp/ipykernel_20735/1217304713.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['TICKET_MEDIO_M3'] = np.where(

#12. Análise exploratória

Distribuição de consumo

In [20]:
px.histogram(
    df,
    x='CONSUMO_ACUMULADO',
    nbins=50,
    title='Distribuição do Consumo Acumulado'
)

Receita acumulada

In [21]:
px.histogram(
    df,
    x='RECEITA_ACUMULADA',
    nbins=50,
    title='Distribuição da Receita Acumulada'
)

# Tipo de hidrômetro x consumo

In [22]:
px.box(
    df,
    x='TIPO_HIDROMETRO',
    y='CONSUMO_ACUMULADO',
    title='Consumo Acumulado por Tipo de Hidrômetro'
)

# Idade x receita

In [23]:
px.scatter(
    df,
    x='IDADE_HIDROMETRO',
    y='RECEITA_ACUMULADA',
    color='TIPO_HIDROMETRO',
    title='Idade do Hidrômetro x Receita'
)

# 13. Indicadores Estratégicos

Tarifa média da base

In [24]:
# TARIFA MEDIA GLOBAL

tarifa_media = (
    df['RECEITA_ACUMULADA'].sum() /
    df['CONSUMO_ACUMULADO'].sum()
)

print(f'Tarifa média da base: R$ {tarifa_media:.2f}/m³')

Tarifa média da base: R$ 12.57/m³

Receita potencial

In [25]:
# RECEITA POTENCIAL

df['RECEITA_POTENCIAL'] = (
    df['CONSUMO_ACUMULADO'] *
    tarifa_media
)

/tmp/ipykernel_20735/293069254.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Perda estimada

In [26]:
# PERDA ESTIMADA

df['PERDA_ESTIMADA'] = (
    df['RECEITA_POTENCIAL'] -
    df['RECEITA_ACUMULADA']
)

/tmp/ipykernel_20735/582253206.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

flag suspeita

In [27]:
# um marcador automático que identifica registros com comportamento fora do padrão esperado

# FLAG DE SUSPEITA

df['FLAG_SUSPEITA'] = np.where(
    (
        df['CONSUMO_ACUMULADO'] >
        df['CONSUMO_ACUMULADO'].quantile(0.75)
    ) &
    (
        df['TICKET_MEDIO_M3'] <
        df['TICKET_MEDIO_M3'].quantile(0.25)
    ),
    'SUSPEITO',
    'NORMAL'
)

df['FLAG_SUSPEITA'].value_counts()

/tmp/ipykernel_20735/676250682.py:5: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

FLAG_SUSPEITA
NORMAL      1815
SUSPEITO      82
Name: count, dtype: int64

Score de prioridade financeira

In [28]:
# SCORE DE PRIORIDADE PARA IDENTIFICAR MAIOR PERDA E HIDROMETROS MAIS ANTIGOS PARA TROCA, FISCALIZAÇÃO E INSPEÇÃO

df['SCORE_PRIORIDADE'] = (
    (
        df['PERDA_ESTIMADA']
        .clip(lower=0)
    ) *
    (
        df['IDADE_HIDROMETRO']
        .fillna(0)
    )
)

/tmp/ipykernel_20735/2547624480.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Ranking financeiro

In [29]:
top_perdas = df.nlargest(
    20,
    'PERDA_ESTIMADA'
)[
    [
        'MATRICULA',
        'TIPO_HIDROMETRO',
        'IDADE_HIDROMETRO',
        'PERDA_ESTIMADA',
        'FLAG_SUSPEITA'
    ]
]

top_perdas

,MATRICULA,TIPO_HIDROMETRO,IDADE_HIDROMETRO,PERDA_ESTIMADA,FLAG_SUSPEITA
416,1371190-3,Unijato,0.80,124986.06,SUSPEITO
1338,1374137-3,Multijato,2.00,45309.20,SUSPEITO
1138,1373937-9,Multijato,2.40,38942.06,SUSPEITO
1096,1373895-0,Multijato,2.60,37392.92,NORMAL
760,1373558-6,ULTRASSÔNICO,9.00,35946.58,SUSPEITO
825,1373624-8,ULTRASSÔNICO,9.40,35822.67,SUSPEITO
824,1373623-0,ULTRASSÔNICO,2.70,33637.91,NORMAL
1599,1374403-8,Multijato,0.70,32260.18,SUSPEITO
826,1373625-6,ULTRASSÔNICO,0.10,31940.46,NORMAL
918,1373717-1,Multijato,0.70,28027.41,SUSPEITO
576,1373365-6,Multijato,0.10,27220.11,SUSPEITO
901,1373700-7,ULTRASSÔNICO,2.00,26214.44,SUSPEITO
1184,1373983-2,Unijato,1.00,25641.38,NORMAL
689,1373485-7,Unijato,0.90,22555.74,SUSPEITO
691,1373487-3,ULTRASSÔNICO,5.80,20069.44,SUSPEITO
1023,1373822-4,Multijato,0.10,19627.81,SUSPEITO
1219,1374018-0,Multijato,2.80,18765.91,NORMAL
900,1373699-0,ULTRASSÔNICO,2.00,18691.36,NORMAL
1157,1373956-5,ULTRASSÔNICO,2.00,17976.14,SUSPEITO
626,1373416-4,Multijato,2.40,17966.64,SUSPEITO

DEMONSTAÇÃO GRAFICA

In [30]:
px.scatter(
    df,
    x='CONSUMO_ACUMULADO',
    y='RECEITA_ACUMULADA',
    color='FLAG_SUSPEITA'
)

## Faixa operacional de vida do parque dos hidrometros

In [32]:
# CLASSIFICACAO OPERACIONAL DOS HIDROMETROS

df['STATUS_HIDROMETRO'] = np.where(
    df['IDADE_HIDROMETRO'] < 5,
    'DENTRO DA VIDA UTIL',
    np.where(
        df['IDADE_HIDROMETRO'] < 7,
        'PROXIMO DO VENCIMENTO',
        'SUBSTITUICAO RECOMENDADA'
    )
)

# Para verificar a distribuição
df['STATUS_HIDROMETRO'].value_counts()

STATUS_HIDROMETRO
DENTRO DA VIDA UTIL         1408
PROXIMO DO VENCIMENTO        349
SUBSTITUICAO RECOMENDADA     140
Name: count, dtype: int64

Visualização Gáfica do PArque de hidrometros

In [33]:
status_hidrometro = (
    df['STATUS_HIDROMETRO']
    .value_counts()
    .reset_index()
)

status_hidrometro.columns = [
    'STATUS',
    'QUANTIDADE'
]

fig = px.bar(
    status_hidrometro,
    x='STATUS',
    y='QUANTIDADE',
    color='STATUS',
    title='Situação Operacional dos Hidrômetros',
    text='QUANTIDADE',
    color_discrete_map={
        'DENTRO DA VIDA UTIL': 'green',
        'PROXIMO DO VENCIMENTO': 'yellow',
        'SUBSTITUICAO RECOMENDADA': 'red'
    }
)

fig.update_traces(
    textposition='outside'
)

fig.update_layout(
    xaxis_title='Status',
    yaxis_title='Quantidade de Hidrômetros',
    showlegend=False
)

fig.show()

STATUS_HIDROMETRO x PERDA_ESTIMADA

In [39]:
# agrupando os dados
dados_linha = (
    df.groupby(
        ['IDADE_HIDROMETRO', 'STATUS_HIDROMETRO']
    )['PERDA_ESTIMADA']
    .mean()
    .reset_index()
)

# criando o comparativo visual
fig = px.line(
    dados_linha,
    x='IDADE_HIDROMETRO',
    y='PERDA_ESTIMADA',
    color='STATUS_HIDROMETRO',
    markers=True,
    title='Perda Estimada x Vida Útil dos Hidrômetros',
    color_discrete_map={
        'DENTRO DA VIDA UTIL': 'green',
        'PROXIMO DO VENCIMENTO': 'yellow',
        'SUBSTITUICAO RECOMENDADA': 'red'
    }
)

fig.update_layout(
    xaxis_title='Idade do Hidrômetro (anos)',
    yaxis_title='Perda Estimada Média (R$)',
    template='plotly_white'
)

fig.show()